server:
  port: 8081

keycloak:
  enabled: true
  auth-server-url: http://localhost:8080
  realm: base-realm
  public-client: false
  resource: spring-boot-app
  credentials:
    secret: 3cIAhceoDDL7agn72DrKeimccTXFLE7f
    
grpc:
  enableReflection: true
  security:
    auth:
      enabled: true

spring:
  security:
    oauth2:
      resourceserver:
        jwt.issuer-uri: http://localhost:8080/realms/base-realm
        